-- Create user table a insert seed user

CREATE TABLE IF NOT EXISTS public.User
(
  Id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  foreName         VARCHAR(100) NOT NULL,
  surName          VARCHAR(100) NOT NULL,
  startDate        DATE         NOT NULL,
  contractHours    INT          NOT NULL,
  bonusEntitlement INT,
  managerId        INT
);

INSERT INTO public.User (foreName, surName, startDate, contractHours, bonusEntitlement)
VALUES ('Duane', 'Taylor,', '1999-11-24', 37, 5);

INSERT INTO public.User(foreName,
                        surName,
                        startDate,
                        contractHours,
                        bonusEntitlement,
                        managerId)
VALUES ('Ida',
        'Herrera', '2020-11-24', 37, 0, 1);

INSERT INTO public.User(foreName,
                        surName,
                        startDate,
                        contractHours,
                        bonusEntitlement,
                        managerId)
VALUES ('Becky', 'Ferguson', '2008-11-24', 37, 3, 1);
